[Tree] : Import my personal config for vince
Signed-off-by: Rama Bondan Prakoso <ramanarubp@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -118,16 +118,17 @@ if [ -f /system/system/build.prop ]; then
   unset root;
 fi;
 
-ui_print "Checking Treble or nah..."
+ui_print "Checking Treble or Not..."
 mount -o rw,remount -t auto /system;
 mount -o rw,remount -t auto /vendor 2>/dev/null;
 if [ "$(file_getprop /system/build.prop ro.treble.enabled)" == "true" ]; then
-  ui_print "Swoosh..."
+  ui_print "Treble..."
   rm -rf /vendor/etc/perf
   dtb=/tmp/anykernel/treble;
 else
-  ui_print="Excuse me, what the duck"
+  ui_print "Non..."
   rm -rf /system/vendor/etc/perf;
+  dtb=/tmp/anykernel/nontreble;
 fi;
 mount -o ro,remount -t auto /system;
 mount -o ro,remount -t auto /vendor 2>/dev/null;
@@ -145,11 +146,10 @@ if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
   abort "Recovery busybox setup failed. Aborting...";
 fi;
 
-# FIXME : penkek requires treble, deprecate this later
-# cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
-# if [ $? != "0" ]; then
-#   abort "DTB append failed. Aborting...";
-# fi;
+cat /tmp/anykernel/kernel/Image.gz $dtb/*.dtb > /tmp/anykernel/Image.gz-dtb;
+if [ $? != "0" ]; then
+  abort "DTB append failed. Aborting...";
+fi;
 
 PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
 if [ $? != "0" ]; then
